// Lista de nombres de productos para autocompletado
export const PRODUCT_NAMES = [
    "Cafe Chico", "Cafe Mediano", "Cafe Doble", "Desayuno Simple", "Desayuno Completo",
    "Desayuno Light", "Desayuno La Central", "Desayuno Tabla Para 2", "Miga", "Pebete",
    "Baguette", "Arabe", "Lomito", "Hamburguesa", "Sandwich De Milanesa",
    "Baguette De Milanesa", "Agregado De Papas", "Porcion De Papas", "Empanadas X Unidad Carne",
    "Empanadas X Unidad Pollo", "Empanadas X Unidad Queso", "Empanadas X6 Carne", "Empanadas X6 Pollo",
    "Empanadas X6 Queso", "Empanadas X12 Carne", "Empanadas X12 Pollo", "Empanadas X12 Queso",
    "Pizzeta Muzzarella", "Pizzeta Napolitana", "Pizzeta Especial", "Pizza Muzzarella",
    "Pizza Napolitana", "Pizza Especial", "Medialunas", "Tortilla", "Menu Ejecutivo",
    "Menu Social", "Menu Economico", "Milanesa Al Plato", "Milanesa A Caballo", "Milanesa Napo",
    "Pollo A La Plancha", "Ensalada Mediterranea", "Ensalada Luna", "Ensalada Cesar",
    "Ensalada Central", "Licuado Vaso Arandano", "Licuado Litro Arandano", "Licuado Vaso Frutilla",
    "Licuado Litro Frutilla", "Licuado Vaso Anana", "Licuado Litro Anana", "Licuado Vaso Durazno",
    "Licuado Litro Durazno", "Licuado Vaso Maracuya", "Licuado Litro Maracuya", "Licuado Vaso Banana",
    "Licuado Litro Banana", "Limonada Vaso", "Limonada Litro", "Submarino", "Capuchino",
    "Te, Mate O Leche", "Medialunas Jyq", "Ensalada De Fruta", "Porcion De Huevo Revuelto",
    "Medicamento Ibuevanol Rapida Accion", "Medicamento Keterolac", "Medicamento Migral",
    "Medicamento Novalgina", "Medicamento Paracetamol", "Medicamento Quraplus", "Medicamento Sertal Perla",
    "Medicamento Sertal Compuesto", "Medicamento Tafirol", "Medicamento Te Vick", "Medicamento Uvasal",
    "Medicamento Actron Mujer", "Medicamento Actron 400", "Medicamento Actron 600", "Medicamento Alikal",
    "Medicamento Bayaspirina C/Fria Limon", "Medicamento Bayaspirina", "Medicamento Cafiaspirina",
    "Medicamento Curitas", "Libreria Goma De Pegar Pelikan 30Ml", "Libreria Lapiz Negro Bic",
    "Libreria Lapicera Bic Trazo Fino", "Libreria Lapicera Bic Trazo Grueso", "Libreria Ojalillo X Unidad Solapa",
    "Libreria Lapicera Filgo Gel Pop Colores", "Libreria Repuesto Simball Roller Tinta Gel Borrable",
    "Libreria Clips X10", "Libreria Lapicera Filgo Borrax 0.7 Mm", "Libreria Lapiz Negro Filgo",
    "Libreria Borrador Cuadrado Grande", "Libreria Borrador Rectangulo", "Libreria Folio A4",
    "Libreria Compas", "Libreria Tijera", "Libreria Corrector Filgo", "Libreria Cuaderno Husares Rayado Y Cuadriculado",
    "Libreria Cinta Adhesiva Grande", "Libreria Cinta Adhesiva Mediana", "Libreria Cinta Adhesiva Chica",
    "Libreria Resaltador Filgo S-Lite", "Libreria Resaltadores Trabi Colores", "Libreria Regla 30Cm Katana",
    "Libreria Fibron Pizarra Travi Colores", "Libreria Fibron Permanente Travi Colores", "Libreria Juego Geometrico",
    "Libreria Cuaderno America Terra Cuadriculado Y Rayado", "Libreria Cartulina", "Libreria Afiche",
    "Libreria Block Avon A4 Rayado Y Cuadriculado", "Helado Bombom Target", "Helado Cono Target Y Cono Bola",
    "Helado Cool Surtido", "Helado Granizado", "Helado Bombom Croc", "Helado Ouch", "Helado Summun Mix",
    "Helado Gran Com Surtidos", "Caramelos De Leche Rellenos", "Caramelos Reloj Acidos",
    "Caramelos De Menta Y Miel", "Caramelos Masticables", "Caramelos Frutales Rellenos",
    "Flyn Paff Surtidos", "Chupetines Evolution", "Topline Chico", "Topline Seven", "Topline Ultra",
    "Beldent Chico", "Beldent Infinit", "Menthoplus", "Menthoplus Acidos", "Menthoplus Zero",
    "Caramelos Cligt", "Halls Surtidos", "Mogul 50Gr", "Mogul 30Gr", "Mogul Rollo", "Bananita Dolca",
    "Marroc", "Pacha Granola Premium", "Pacha Granola Clasica", "Pacha Mix Frutos Secos",
    "Pacha Barras De Cereal", "Cereal Mix Barra De Cereal Surtida", "Turron Surtido", "Garrapiñadas",
    "Chizitos", "Pochoclos De Maiz Y Trigo 90 Gr.", "Toallas Ladysoft", "Papel Higienico Por Unidad",
    "Yerba Mate Mañanita 500 Gr.", "Yerba Mate Taragui", "Marinaro Vidrio Surtido", "Cigarro Suelto",
    "Encendedor", "Miga Tostado", "Baguette Tostado", "Pebete Tostado", "Arabe Tostado",
    "Galletas Salvado Hogareñas X3", "Pañuelitos Elite", "Surtido Diversion", "Obleas Bon O Bon Surtidas",
    "Pepas Aire De Lujan", "Galletas Hogareñas Surtidas", "Porcion De Tostadas", "Medialunas Desayuno",
    "Tortilla Desayuno", "Aquarius Pera 500Ml", "Postre", "Aquarius Pomelo Amarillo 1,5 L",
    "Agua Para Termo", "Libreria Borrador Cuadrado Chico", "Baggio Chico", "Chocolatada",
    "Promo Baguette Milanesa + Fanta 375Ml", "Cepita 300Ml", "Porcion Ensalada Mixta", "Hielo",
    "Agregado De Huevos X2", "Medicamento Rolfita Limon", "Chupetines Pops Frutales",
    "Porcion Fetas Fiambre", "Azucar X 1Kg", "Alfajor Rasta", "Gomitas", "Cepita 1.5",
    "Te En Saquito", "Queso Untable / Mermelada", "Libreria Regla 20Cm", "Medicamento Refrianex",
    "Medicamento Diclofenac", "Medicamento Loratadina", "Medicamento Omeprazol", "Manzana Fruta",
    "Banana Fruta", "Mandarina Fruta", "Edulcorante Liquido", "Pera Fruta", "Libreria Mina Faber 0.5 2B",
    "Libreria Tabla Periodica", "Libreria Hojas De Calcar", "Libreria Hojas Para Calcar C/U",
    "Galletas Valenciano Surtido", "Alfajor Cofler X3", "Mandarina X4", "Billiken 30Gr Surtido",
    "Vasos Descartables", "Cafe Para Llevar", "Naranja Fruta", "Bolsa Caramelos", "Alfajor Chocotorta",
    "Barra Zannas Surtido", "Libreria Lapiz Negro Bic C/ Borrador", "Libreria Mapas", "Barbijos",
    "Guantes De Nitrilo", "Guantes De Nitrilo C/U", "Mani Salado", "Promo Baguette De Mila C/Papas",
    "Barra Merlin Surtido", "Barra Merlin Proteica", "Snack Arroz Pizza", "Tostadas Arroz Sin Sal Dh",
    "Papas Quento Surtido", "Menu Evento", "Promo Tafi Jalapeño+ Coca 250", "Alfajor Sin Tacc",
    "Alfajor Rasta Trico", "Te Para Llevar", "Desayuno Bienestar", "Arabe De Milanesa",
    "Promo Pizzeta Muzza + Fanta 500", "Promo Pizzeta Muzza + Fanta 375", "Vasos Termicos",
    "Toallita Por Unidad", "Factura Rellena", "Coca Cola 250Ml", "Bocadito Chocomani",
    "Bocadito Vaca Lechera", "Alfajor Marley Surtido", "Alfajor Marley Triple", "Libreria Sobres Chicos",
    "Libreria Sobres Grandes", "Medicamento Buscapina Fem", "Pan De Salvado", "Pebete De Pollo",
    "Baguette De Pollo", "Gomitas Mogul Extreme", "Libreria Portamina Filgo", "Libreria Mina Faber 0.5B",
    "Alfajor Tofi Triple", "Alfajor El Arriero Surtido", "Menu Ejecutivo Evento", "Brownies",
    "Libreria Transportador", "Fiambre Jyq X200gr", "Grafitti Oferta", "Removedores De Cafe X40",
    "Vainillas", "Mini Rocklets", "Promo Baguette+Coca Zero 375", "Citric 1L X14", "Extra Queso",
    "Libreria Cinta De Papel", "Libreria Hoja De Maquina X20", "Libreria Carpeta A4", "Libreria Sacapuntas",
    "Porcion De Huevo Revuelto C/ Jyq", "Flow Cereal Varias", "Billiken Gomitas 150Gr Surtidos",
    "Alquiler Juegos Didacticos", "Cafe Instantaneo", "Chocolinas 250Gr Surtidos", "Tivis Felfort",
    "Chicle Bubbaloo", "Magdalena Valente 215Gr Surtido", "Bolsa De Gomitas Dinosaurio 2X500",
    "Bolsa Gomitas", "Cucharitas De Plastico X50", "Factura Rellena Con Desayuno",
    "Magdalena Gaona 215Gr Surtido", "Tira Fizz", "Huevo X Unidad", "Libreria Repuesto De Tinta",
    "Medicamento Te Gripaben", "Libreria Mapa Argentina", "Mani Bañado Arcor",
    "Promo Baguette Mila Mas Sprite 375", "Korn Barra", "Libreria Mina Faber 0.7Hb",
    "Promo Bc Y Aires De Lujan", "Fanta Naranja Promo 1.5L", "Jugo De Naranja Grande",
    "Magdalena Don Satur 200 Gr Surtido", "Bolsa De Caramelo Surtido", "Cigarillos Suelto Xl",
    "Jugo De Naranja Chico", "Mantecol 64Gr", "Libreria Repuesto Pizzini", "Pañuelitos Cata",
    "Billiken X3", "Sandwich Pan Integral", "Power Naranja Promo", "Tortitas Black 125G",
    "Azucar En Sobre X3", "Libreria Boligrafo Roller Borrable Pizzini", "Libreria Portamina 0.5 Filgo",
    "Cofler Air Blanco Oferta", "Librería Fibron Filgo Colores", "Escuadra (Juego Geometrico)",
    "Pipas Clasicas Promo", "Oreo Chocolate , Mani X 118Gr", "Gomitas Chicas 3X100",
    "Galleta Oreo Clásica Frutilla 118gr",
    "Galletas Aires De Lujan", "Evento X 70 Personas $8500", "Bolsa Moritas",
    "Medicamento Buscapina Compuesta", "Librería Sobre Chico", "Magdalenas C/U", "Helado Bombom",
    "Chocolate Arcor Air 27G Promo", "Cubanitos", "Cafe Mediano Con Magdalena", "Milka Surtido 55Gr",
    "Alfajor Tatin X3 Surtido", "Alfajor Tatin Simple", "Alfajor Fulbito", "Opera 55G", "Opera 92G",
    "Alfajor Terrabusi Triple Surtido", "Dos Corazones", "Alfajor Tita Simple", "Alfajor Pepito Triple",
    "Marlboro Uva Xl", "Alfajor Tri Shot X3", "Bon O Bon Surtidos", "Marlboro Coral Xl", "Tita",
    "Alfajor Oreo Triple", "Marlboro Uva X12", "Cofler Block 38Gr", "Marlboro Red Box 12",
    "Marlboro Crafted Box 20", "Marlboro Crafted Ks", "Marlboro Crafted Azul Box",
    "Marlboro Crafted Coral Box", "Marlboro Azul Crafted Ks", "Rhodesia", "Medicamento Buscapina Perla",
    "Caramelo Cremino", "Promo Pizzeta Mas Jugo", "Snacky Terrabusi", "Librería Sobre Grande",
    "Promo Jugo Bc Y Pepas Aires De Lujan", "Mantecol X 26Gr", "Nugaton", "Galletas Cofler Rellenas 85G",
    "Evento Agosto 2025 Bienestar", "Pochoclos Semix Dulce", "Barra Que Lo Paleo Surtido",
    "Tafi 65Gr.", "Barra Donys", "Alfajor Membrillo Titito", "Tafi 100Gr. Surtido", "Pacha Saladitos",
    "Libreria Escuadra Maped", "Takis 49G", "Terrabusi Chips", "Terrabusi Scons", "Jugo En Polvo Naranja",
    "Oreo 118Gr", "Pepitos", "Surtido Terrabusi", "Terrabusi Boca De Dama", "Alfajor Manon",
    "Chocolate Milka Oreo 20G", "Habanitos Promo", "Mini Rhodesia", "Alfajor Milka Mousse Blanco Y Negro",
    "Melba", "Baggio Grande", "Si Diet 250Ml", "Si Diet 200Ml", "Kesitas Bolsa", "Galletas Rocklets",
    "Galletas Cofler Block", "Porteñitas", "Mana Rellenas Surtidos", "Sonrisas", "Alfajor Aguila Surtido",
    "Cereal Mix Galletas Surtido", "Pepas Recetas De La Abuela", "Mana Liviana Surtidas", "Merengadas",
    "Formis 72G Surtidas", "Formis 102G Surtidas", "Saladix Caja Surtido", "Chocolinas 170Gr",
    "Chocolinas 100Gr", "Coquitas", "Rumba 110G", "Amor 110G", "Mellizas 110G", "Serranitas",
    "Traviata, Rex Y Kesitas", "Kesitas Familiar", "Traviata", "Traviata X3", "Surtido Bagley",
    "Kesitas Caja", "Alfajor Bagley Blanco Y Negro", "Alfajor Bon O Bon Triple", "Rex Caja",
    "Alfajor Chocoarroz 22Gr", "Rex Bolsa", "Saquito De Te O Mate", "Feeling Felfort", "Mentitas 16Gr",
    "Nucrem 84Gr", "Yerba Union 500Gr", "Cofler Air 27Gr Surtido", "Holanda", "Oblea Xl Surtidas",
    "Rocklets 35Gr", "Graffiti Surtido", "Cofler Chocolinas", "Arcor Twit", "Saladix Bolsa Surtido",
    "Rocklets 20Gr", "Chocolate Arcor 25Gr Surtido", "Tofi Surtidos", "Coca Cola 1,5 L", "Sprite 1,5 L",
    "Fanta 1,5 L", "Coca Cola 500Ml", "Sprite 500 Ml.", "Fanta 500 Ml.", "Coca Cola 375 Ml.",
    "Aquarius Pomelo Rosado 500 Ml.", "Aquarius Pomelo Rosado 1,5 L", "Coca Cola Zero 375 Ml.",
    "Aquarius Limonada 1.5", "Fanta 375 Ml.", "Sprite 375 Ml.", "Coca Cola Zero 500Ml",
    "Coca Zero 1,5 L", "Aquarius Manzana 500 Ml.", "Aquarius Pomelo Amarillo 500 Ml.",
    "Aquarius Pera 1,5 L", "Aquarius Manzana 1,5", "Aquarius Naranja 500 Ml.", "Aquarius Naranja 1,5 L",
    "Agua Benedictina", "Soda Benedictina", "Power Surtido", "Tostadas De Arroz Molinos Ala",
    "Pepas Trio", "Mecano Bonafide Dl", "Mecano Bonafide Nugaton", "Yogurt Manfrey Surtido",
    "Yogurt Con Cereal", "Helado Yo Crok", "Marinaro Ice Surtidas", "Soda Marinaro", "Agua Marinaro",
    "Tonica", "Don Satur Saladas", "Don Satur Dulces", "Pipas Gigantes", "Citric Surtido 500Ml",
    "Rapsodia Minitorta", "Libreria Transportador Filgo", "Speed Chico", "Speed Zero Chico",
    "Speed Zero", "Tostadas A La Mesa Surtidas", "Medicamento Tafirol Espasmo", "Mani King Saborizado",
    "Mani King Salado Con Piel Y Sin Piel", "Agua Misiones", "Soda Misiones", "Agua Misiones 1,5 L",
    "Tostaditos Quento Surtidas", "Palitos Salados", "Alfajor Chocolate Blanco", "Monster Surtidos",
    "Speed 473 Ml."
];
